name: Crm API Github Action

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker-compose up -d

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      with:
        heroku_api_key: bbabc279-8e34-480b-a2f5-cf213042be3c
        heroku_app_name: 'crm-api-docker'
        heroku_email: 'sabinshrestha292@gmail.com'
